### ISSUE TITLE
"int object is not callable" error when running sta_connect_example.py

### ISSUE THREAD

**Issue by atmalagon** [greearb/lanforge-scripts#4]
Sorry for spamming, but just wanted to note that running sta_connect_example on my setup seems to fail when trying to finish the connection (the only things I changed in the script were putting in my own ssid and password values, and also adding sleep statements between setup() and start(), and between stop() and finish())

```
$ python3 sta_connect_example.py
Adding new stations  sta000,
Configuring
 sta000,
Bringing ports up...
Waiting until  ports appear admin-up...
Waiting for 1 stations to associate to AP: .... sta000 +AP 84:80:94:B0:05:76,
Starting CX Traffic
Refresh CX stats
Stopping CX Traffic
Traceback (most recent call last):
  File "sta_connect_example.py", line 51, in <module>
    main()
  File "sta_connect_example.py", line 35, in main
    staConnect.finish()
TypeError: 'int' object is not callable
```

**Comment by matthewstidham** [comment]
I got the same error when I ran it on my system, because its default port is eth2. I changed it to eth1 to match my device, I'm going to work on this tomorrow.

**Comment by matthewstidham** [comment]
OK, I just pushed some modifications. Set flags for the eth port you are using and network credentials which you use on your system and let me know if that works for you. If you need or want assistance, contact me and I can walk you through it over a video call.

**Comment by atmalagon** [comment]
Thank you so much Matthew! I no longer get the "int object is not callable" error when running on the latest commit; for some reason the call to set_port always fails for me with a 400 error so I have to manually click DHCP for my test station (I thought this was a timing issue and increased the sleep between adding the station and configuring it in sta_connect.py to 1 second, but saw no difference) but after that the test will continue working :) It seems to have some difficulty in the cleanup (tries to remove the UDP endpoints repeatedly it looks like), but maybe there's something specific about my setup that's causing it to struggle. 
```
[lanforge@ct525-f314 py-scripts]$ ./sta_connect_example.py -u "eth1.3" --ssid "Acme1" --passwd "123456789" --security wpa2
Adding new stations  sta000,
Configuring
 sta000,----- LFRequest::json_post:147 HTTPError: --------------------------------------------
<http://localhost:8080/cli-json/set_port> HTTP 400: Bad Request
Error:  <class 'urllib.error.HTTPError'>
Request URL: http://localhost:8080/cli-json/set_port
Request Content-type: application/json
Request Accept: application/json
Request Data:
(b'{"shelf": 1, "resource": 1, "current_flags": 2147483648, "interest": 16386, '
 b'"port": "sta000", "suppress_preexec_cli": false, "suppress_preexec_method": '
 b'false, "suppress_postexec_cli": true, "suppress_postexec_method": true}')
Response Connection: close
Response Content-Length: 111
Response Content-Type: application/json
Response Date: Wed, 24 Mar 2021 17:52:29 GMT
Response X-Error-0: baseCheckPortExists: phantom port: 1.1.8
Response X-Error-1: unable to execute set_port
------------------------------------------------------------------------

Bringing ports up...
Waiting until  ports appear admin-up...
Waiting for 1 stations to associate to AP: .................. sta000 +AP 84:80:94:B0:05:76,
Starting CX Traffic
Refresh CX stats
Stopping CX Traffic
----- LFRequest::json_post:147 HTTPError: --------------------------------------------
<http://localhost:8080/cli-json/rm_endp> HTTP 400: Bad Request
Error:  <class 'urllib.error.HTTPError'>
Request URL: http://localhost:8080/cli-json/rm_endp
Request Content-type: application/json
Request Accept: application/json
Request Data:
b'{"endp_name": "testUDP-sta000-A"}'
Response Connection: close
Response Content-Length: 106
Response Content-Type: application/json
Response Date: Wed, 24 Mar 2021 17:54:10 GMT
Response X-Error-0: endpoint not found: testUDP-sta000-A
Response X-Error-1: unable to execute rm_endp
------------------------------------------------------------------------
----- LFRequest::json_post:147 HTTPError: --------------------------------------------
<http://localhost:8080/cli-json/rm_endp> HTTP 400: Bad Request
Error:  <class 'urllib.error.HTTPError'>
Request URL: http://localhost:8080/cli-json/rm_endp
Request Content-type: application/json
Request Accept: application/json
Request Data:
b'{"endp_name": "testUDP-sta000-B"}'
Response Connection: close
Response Content-Length: 106
Response Content-Type: application/json
Response Date: Wed, 24 Mar 2021 17:54:10 GMT
Response X-Error-0: endpoint not found: testUDP-sta000-B
Response X-Error-1: unable to execute rm_endp
------------------------------------------------------------------------
Tests pass
```

**Comment by atmalagon** [comment]
Ah, please ignore the comment above about set_port failures -- after bumping up the timeout to 30s between adding a station and configuring, set_port succeeds. Still get the "unable to execute rm_endp" failures on unknown UDP endpoints, but otherwise all good :)

**Comment by atmalagon** [comment]
will do!
